config/routes.rb
Rails.application.routes.draw do
  resources :envoyers
  root 'fichier_reclamations#index'
  resources :user_reclamations
  resources :fichier_reclamations
  resources :fichiers
  resources :reclamations
  devise_for :views
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fichier_reclamation.rb
class FichierReclamation < ApplicationRecord
  belongs_to :reclamation
  belongs_to :fichier
end

app/controllers/fichier_reclamations_controller.rb
class FichierReclamationsController < ApplicationController
  before_action :set_fichier_reclamation, only: [:show, :edit, :update, :destroy]

  # GET /fichier_reclamations
  # GET /fichier_reclamations.json
  def index
    @fichier_reclamations = FichierReclamation.all
    unless current_user
      redirect_to new_user_session_path
    else
      if current_user.is_admin
        redirect_to user_reclamations_path
      end
      @reclamations = Reclamation.all
      @btn = ["default","warning","danger","primary","success"]
    end
  end

  # GET /fichier_reclamations/1
  # GET /fichier_reclamations/1.json
  def show
    @valides = UserReclamation.where(resolu: true)
  end

  # GET /fichier_reclamations/new
  def new
    @fichier_reclamation = FichierReclamation.new
  end

  # GET /fichier_reclamations/1/edit
  def edit
  end

  # POST /fichier_reclamations
  # POST /fichier_reclamations.json
  def create
    @fichier_reclamation = FichierReclamation.new(fichier_reclamation_params)

    respond_to do |format|
      if @fichier_reclamation.save
        format.html { redirect_to @fichier_reclamation, notice: 'Fichier reclamation was successfully created.' }
        format.json { render :show, status: :created, location: @fichier_reclamation }
      else
        format.html { render :new }
        format.json { render json: @fichier_reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichier_reclamations/1
  # PATCH/PUT /fichier_reclamations/1.json
  def update
    respond_to do |format|
      if @fichier_reclamation.update(fichier_reclamation_params)
        format.html { redirect_to @fichier_reclamation, notice: 'Fichier reclamation was successfully updated.' }
        format.json { render :show, status: :ok, location: @fichier_reclamation }
      else
        format.html { render :edit }
        format.json { render json: @fichier_reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichier_reclamations/1
  # DELETE /fichier_reclamations/1.json
  def destroy
    @fichier_reclamation.destroy
    respond_to do |format|
      format.html { redirect_to fichier_reclamations_url, notice: 'Fichier reclamation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fichier_reclamation
      @fichier_reclamation = FichierReclamation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fichier_reclamation_params
      params.require(:fichier_reclamation).permit(:reclamation_id, :fichier_id)
    end
end

app/helpers/fichier_reclamations_helper.rb
module FichierReclamationsHelper
end

app/views/fichier_reclamations/_form.html.erb
<%= form_with(model: fichier_reclamation, local: true) do |form| %>
  <% if fichier_reclamation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fichier_reclamation.errors.count, "error") %> prohibited this fichier_reclamation from being saved:</h2>

      <ul>
        <% fichier_reclamation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :reclamation_id %>
    <%= form.text_field :reclamation_id %>
  </div>

  <div class="field">
    <%= form.label :fichier_id %>
    <%= form.text_field :fichier_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fichier_reclamations/edit.html.erb
<h1>Editing Fichier Reclamation</h1>

<%= render 'form', fichier_reclamation: @fichier_reclamation %>

<%= link_to 'Show', @fichier_reclamation %> |
<%= link_to 'Back', fichier_reclamations_path %>

app/views/fichier_reclamations/index.html.erb
    <header>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <a href="#" style="background-color: transparent;">
              <img src="/vendor/images/logo2.PNG" alt="logo" height="100vh">
            </a>
          </div>  <!-- End of /.col-md-12 -->
        </div>  <!-- End of /.row -->
      </div>  <!-- End of /.container -->
    </header> <!-- End of /Header -->

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-9 clearfix">
            <ul >
                <li>
                    <div class="blog-box" style="background-color: rgba(0,0,0,0.5);">
                        
                        <div class="blog-post-body clearfix">
                          <a href="blog-single.html">
                            <h2 style="text-align: center;">Veuillez choisir votre type de réclamation</h2>
                          </a>

                          <% @reclamations.each_with_index do |typa, x| %>
                            <div class=" container" style=" margin-bottom: 15px;">
                              <a href="#" style="width: 100%; font-size: 1.5em; color: #fff; background-color: <%= typa.couleur %>" class="btn btn-default" data-toggle="modal" data-target="#mod<%= typa.id %>"><%= typa.titre %></a>
                            </div>
                          <% end %>
                          
                        </div>
                    </div>  <!-- End of /.blog-box -->
                </li>
                
              </ul> <!-- End of /.blog-zone -->

          </div>  <!-- End of /.col-md-9 -->

          <div class="col-md-3" style="background-color: rgba(0,0,0,0.5);">
            <div class="blog-sidebar">
              <div class="block vert">
                    <div id="my-calendar" style="color: #74a339;"></div>
              </div>  <!-- End of /.block -->
            </div>  <!-- End of /.blog-sidebar -->
          </div>  <!-- End of /.col-md-3 -->
        </div>  <!-- End of /.row -->
      </div>  <!-- End of /.container -->
    </section>  <!-- End of /#Blog -->

  <% Reclamation.all.each do |t| %>
    <div class="modal fade" id="mod<%= t.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="container">
            <div class="container" style="width: 100%; text-align: center;">
                <h3 style="color: <%= t.couleur %>"><%= t.titre %></h3>
                <div class="form_content clearfix">
                  <hr>
                  <div class="container text-left">
                    <% t.fichier_reclamations.each_with_index do |ft, y| %>
                      <% if ft.fichier.titre == "Acte d’imposition" %>
                        <div>
                          <h5><i class="fa fa-file" style="color: <%= t.couleur %>"></i> Acte d’imposition</h5>
                          <div class="container" style="margin-left: 10%; width: 90%;">
                            
                            <div class="row">
                              <div class="col-md-6">
                                <input onclick="mampisehoInput<%= t.id %>()" type="checkbox" name="Déclaration (DE)">Déclaration (DE)
                              </div>
                              <div class="col-md-6">
                                <input onclick="mampisehoInput<%= t.id %>()" type="checkbox" name="Déclaration (DE)">Notification définitive
                              </div>
                              <div class="col-md-6">
                                <input onclick="mampisehoInput<%= t.id %>()" type="checkbox" name="Déclaration (DE)">Taxation d’office
                              </div>
                              <div class="col-md-6">
                                <input onclick="mampisehoInput<%= t.id %>()" type="checkbox" name="Déclaration (DE)">Avis d’imposition (IFT/IFPB)
                              </div>
                            </div>
                          </div>
                          <input onchange="miditra<%= ft.fichier.id %>_<%= ft.id %>(this)" type="hidden" id="apotra<%= t.id %>" name="<%= ft.fichier.id %>" class="form-control lokoMaron" accept=".pdf, .jpg, .png" style="margin-left: 10%; width: 90%;">
                        </div>
                      <% else %>
                        <div>
                          <h5><i class="fa fa-file" style="color: <%= t.couleur %>"></i> <%= ft.fichier.titre %></h5>
                          <input id="inp<%= ft.fichier.id%>_<%= y %>_<%= t.id %>" type="file" name="<%= ft.fichier.id %>" class="form-control lokoMavo" accept=".pdf, .jpg, .png" onchange="miditra<%= ft.fichier.id %>_<%= ft.id %>(this)" style="margin-left: 10%; width: 90%;">
                        </div>
                      <% end %>
                    <% end %>
                
                  </div>
                  <br>  
                  <button class="btn btn-default" style="background-color: <%= t.couleur %>" data-dismiss="modal" onclick="sub<%= t.id %>()">Valider</button>  
                </div>
            </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
              </div>
          </div>
        </div>
    </div>
  <% end %>

  <% Reclamation.all.each do |t| %>
    <%= form_tag user_reclamations_path, method: :post, :multipart =>"true" , :id=>"form#{t.id}" do%>
    <input type="hidden" name="typ<%= t.id %>" id="doc<%= t.id %>">
      <% t.fichier_reclamations.each do |ft| %>
        <% if ft.fichier.titre == "Acte d’imposition" %>
          <input type="hidden" name="<%= ft.fichier.id %>" id="hid<%= ft.fichier.id %>hid<%= ft.id %>" >
        <% else %>
          <input type="hidden" name="<%= ft.fichier.id %>" id="hid<%= ft.fichier.id %>hid<%= ft.id %>" >
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <script type="text/javascript">

    <% Reclamation.all.each do |t| %>
      <% t.fichier_reclamations.each_with_index do |ft, y| %>
        function miditra<%= ft.fichier.id %>_<%= ft.id %> (inp) {
          console.log(inp.value);

            if (inp.files && inp.files[0]) {
              var FR= new FileReader();
              
              FR.addEventListener("load", function(e) {
                document.getElementById('hid<%= ft.fichier.id %>hid<%= ft.id %>').value = e.target.result;
              }); 
              
              FR.readAsDataURL( inp.files[0] );
            }
        }
      <% end %>
    <% end %>
    <% Reclamation.all.each do |t| %>

      function mampisehoInput<%= t.id %>(){
        document.getElementById('apotra<%= t.id %>').type = "file";
      }

      function sub<%= t.id %>() {

        if (document.getElementById('apotra<%= t.id %>') && document.getElementById('apotra<%= t.id %>').value == "") {
            alert("Veuillez inserer l'acte d'imposition");
          }

        <% t.fichier_reclamations.each_with_index do |ft, y| %>
          else if (document.getElementById('inp<%= ft.fichier.id %>_<%= y %>_<%= t.id %>') && document.getElementById('inp<%= ft.fichier.id %>_<%= y %>_<%= t.id %>').value == "") {
            alert("Veuillez inserer <%= ft.fichier.titre %>");
          }
        <% end %>

        else{
          document.getElementById('doc<%= t.id %>').value = <%= t.id %>;
          document.getElementById('form<%= t.id %>').submit();
        }
      }

    <% end %>

  </script>

app/views/fichier_reclamations/new.html.erb
<h1>New Fichier Reclamation</h1>

<%= render 'form', fichier_reclamation: @fichier_reclamation %>

<%= link_to 'Back', fichier_reclamations_path %>

app/views/fichier_reclamations/show.html.erb
  <nav class="navbar navbar-default" style="background-color: #fff; box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.7); margin-bottom: 0px;">
    <div >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!-- End of /.navbar-header -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-main" style="text-align: left;">
              <li><a href="/" style=" padding: 0px;"><img src="/vendor/images/logo.png" style="height: 80px;"></a></li>
                <li><a style="color: black; margin: 0px;" href="/">ACCUEIL</a></li>

              <!-- Dropdown Recrutement -->
              <li class="dropdown">
                  <a href="#" style="color: black; margin: 0px;">
                    RECLAMATION
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <% Reclamation.all.order(:titre).each do |r| %>
                      <li><a href="<%= reclamation_path(r.id) %>"><%= r.titre %></a></li>
                    <% end %>
                  </ul>
              </li> 
              <li>
                <a style="color: black; margin: 0px;" href="<%= fichier_reclamation_path(1) %>">
                  <% if UserReclamation.where(resolu: true).count > 1 %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATIONS VALIDEES
                  <% else %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATION VALIDEE
                  <% end %>
                </a>

              </li>
            </ul> <!-- End of /.nav-main -->
        </div>  <!-- /.navbar-collapse -->
    </div>  <!-- /.container-fluid -->
    <div style="position: fixed; right: 20px; top: 20px; color: #fff;">
      <a href="#" class="btn btn-default" data-toggle="modal" data-target="#myModalDecon" style="border-radius: 50%;"><i class="fa fa-user fa-2x"></i></a>
    </div>
  </nav>  <!-- End of /.nav -->


<section>
  <br>

  	<div class="container" style="border: solid; border-width: 1px; border-color: #fff; background-color: rgba(0,0,0,0.5 ); min-height: 80vh;">
      <div style="background-color: #fff; text-align: center;">
        <% if @valides.count > 0 %>
          <div style="position: absolute; background-color: red; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @valides.count %></h5>
          </div>
        <% end %>
        <h5>Réclamations validées</h5>
      </div>
      <% @valides.reverse.each do |n| %>
    	<div class="col-md-4">
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= n.reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><output id="daty_<%= n.id %>"></output> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
</section>

<script type="text/javascript">
  <% @valides.each do |n| %>
    var vokany = mampisehoDaty("<%= n.created_at.to_date.strftime("%d-%m-%y").to_s %>");
    document.getElementById("daty_<%= n.id %>").value = vokany;
  <% end %>
</script>