config/routes.rb
Rails.application.routes.draw do
  resources :envoyers
  root 'fichier_reclamations#index'
  resources :user_reclamations
  resources :fichier_reclamations
  resources :fichiers
  resources :reclamations
  devise_for :views
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_reclamation.rb
class UserReclamation < ApplicationRecord
  belongs_to :user
  belongs_to :reclamation
  has_many :envoyers
end

app/controllers/user_reclamations_controller.rb
class UserReclamationsController < ApplicationController
  before_action :set_user_reclamation, only: [:show, :edit, :update, :destroy]

  # GET /user_reclamations
  # GET /user_reclamations.json
  def index
    @user_reclamations = UserReclamation.all
    @nouvelles = UserReclamation.where(vue: false)
    @attentes = UserReclamation.where(vue: true ,resolu: false)

    # def mampisehoDaty(daty)
    #   andro = daty[0] + daty[1]
    #   volana = (daty[3] + daty[4]).to_i
    #   taona = daty[6] + daty[7]
    #   case volana
    #     when 1
    #       volana = "Janvier"
    #     when 2
    #       volana = "Fevrier"
    #     when 3
    #       volana = "Mars"
    #     when 4
    #       volana = "Avril"
    #     when 5
    #       volana = "Mai"
    #     when 6
    #       volana = "Juin"
    #     when 7
    #       volana = "Juillet"
    #     when 8
    #       volana = "Août"
    #     when 9
    #       volana = "Septembre"
    #     when 10
    #       volana = "Octobre"
    #     when 11
    #       volana = "Novembre"
    #     when 12
    #       volana = "Décembre"
    #   end
    #   valiny = andro + " " + volana + " 20" + taona
    #   return valiny
    # end
  end

  # GET /user_reclamations/1
  # GET /user_reclamations/1.json
  def show
    if current_user.is_admin == true && @user_reclamation.vue != true
      @user_reclamation.update(vue: true)
    end
  end

  # GET /user_reclamations/new
  def new
    @user_reclamation = UserReclamation.new
  end

  # GET /user_reclamations/1/edit
  def edit
  end

  # POST /user_reclamations
  # POST /user_reclamations.json
  def create

    Reclamation.all.each do |t|
        if params[:"typ#{t.id}"]
          @user_reclamation = UserReclamation.create(
            reclamation_id: params[:"typ#{t.id}"],
            user_id: current_user.id,
            vue: false,
            resolu: false
          )
          t.fichier_reclamations.each do |ft|
            Envoyer.create(user_reclamation_id: @user_reclamation.id, 
                          titre: ft.fichier.titre ,
                          contenu: params[:"#{ft.fichier.id}"] )
          end
        end

    end

    redirect_to @user_reclamation, notice: 'Réclamation envoyée.'
    
    # @user_reclamation = UserReclamation.new(user_reclamation_params)

    # respond_to do |format|
    #   if @user_reclamation.save
    #     format.html { redirect_to @user_reclamation, notice: 'User reclamation was successfully created.' }
    #     format.json { render :show, status: :created, location: @user_reclamation }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user_reclamation.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /user_reclamations/1
  # PATCH/PUT /user_reclamations/1.json
  def update
    @user_reclamation.update(resolu: true)
    redirect_to @user_reclamation, notice: 'Réclamation validée avec succès.'
  end

  # DELETE /user_reclamations/1
  # DELETE /user_reclamations/1.json
  def destroy
    @user_reclamation.destroy
    respond_to do |format|
      format.html { redirect_to user_reclamations_url, notice: 'Réclamation supprimée' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_reclamation
      @user_reclamation = UserReclamation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_reclamation_params
      params.require(:user_reclamation).permit(:user_id, :reclamation_id, :date, :vue, :resolu)
    end
end

app/helpers/user_reclamations_helper.rb
module UserReclamationsHelper
end

app/views/user_reclamations/_form.html.erb
<%= form_with(model: user_reclamation, local: true) do |form| %>
  <% if user_reclamation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_reclamation.errors.count, "error") %> prohibited this user_reclamation from being saved:</h2>

      <ul>
        <% user_reclamation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :reclamation_id %>
    <%= form.text_field :reclamation_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :vue %>
    <%= form.check_box :vue %>
  </div>

  <div class="field">
    <%= form.label :resolu %>
    <%= form.check_box :resolu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_reclamations/edit.html.erb
<h1>Editing User Reclamation</h1>

<%= render 'form', user_reclamation: @user_reclamation %>

<%= link_to 'Show', @user_reclamation %> |
<%= link_to 'Back', user_reclamations_path %>

app/views/user_reclamations/index.html.erb
  <nav class="navbar navbar-default" style="background-color: #fff; box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.7); margin-bottom: 0px;">
    <div >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!-- End of /.navbar-header -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-main" style="text-align: left;">
              <li><a href="/" style=" padding: 0px;"><img src="/vendor/images/logo.png" style="height: 80px;"></a></li>
                <li><a style="color: black; margin: 0px;" href="/">ACCUEIL</a></li>

              <!-- Dropdown Recrutement -->
              <li class="dropdown">
                  <a href="#" style="color: black; margin: 0px;">
                    RECLAMATION
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <% Reclamation.all.order(:titre).each do |r| %>
                      <li><a href="<%= reclamation_path(r.id) %>"><%= r.titre %></a></li>
                    <% end %>
                  </ul>
              </li> 
              <li>
                <a style="color: black; margin: 0px;" href="<%= fichier_reclamation_path(1) %>">
                  <% if UserReclamation.where(resolu: true).count > 1 %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATIONS VALIDEES
                  <% else %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATION VALIDEE
                  <% end %>
                </a>

              </li>
            </ul> <!-- End of /.nav-main -->
        </div>  <!-- /.navbar-collapse -->
    </div>  <!-- /.container-fluid -->
    <div style="position: fixed; right: 20px; top: 20px; color: #fff;">
      <a href="#" class="btn btn-default" data-toggle="modal" data-target="#myModalDecon" style="border-radius: 50%;"><i class="fa fa-user fa-2x"></i></a>
    </div>
  </nav>  <!-- End of /.nav -->


<section>
  <br>
  <div class="container" style="border: solid; border-width: 1px; border-color: #fff; background-color: rgba(0,0,0,0.5 ); min-height: 80vh;">
    <div class="col-md-6">
      <div style="background-color: #fff; text-align: center;">
        <% if @nouvelles.count > 0 %>
          <div style="position: absolute; background-color: red; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @nouvelles.count %></h5>
          </div>
        <% end %>
        <h5>Nouvelles réclamations</h5>
      </div>
      <% @nouvelles.each do |n| %>
        <div>
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= n.reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><output id="daty_<%= n.id %>"></output> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <div style="background-color: #fff; text-align: center;">
        <% if @attentes.count > 0 %>
          <div style="position: absolute; background-color: red; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @attentes.count %></h5>
          </div>
        <% end %>
        <h5>Réclamations en attentes</h5>
      </div>
      <% @attentes.each do |n| %>
        <div>
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= n.reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><output id="daty_<%= n.id %>"></output> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script type="text/javascript">
  <% @attentes.each do |n| %>
    var vokany = mampisehoDaty("<%= n.created_at.to_date.strftime("%d-%m-%y").to_s %>");
    document.getElementById("daty_<%= n.id %>").value = vokany;
  <% end %>

  <% @nouvelles.each do |n| %>
    var vokany = mampisehoDaty("<%= n.created_at.to_date.strftime("%d-%m-%y").to_s %>");
    document.getElementById("daty_<%= n.id %>").value = vokany;
  <% end %>
</script>

app/views/user_reclamations/new.html.erb
<h1>New User Reclamation</h1>

<%= render 'form', user_reclamation: @user_reclamation %>

<%= link_to 'Back', user_reclamations_path %>