config/routes.rb
Rails.application.routes.draw do
  resources :envoyers
  root 'fichier_reclamations#index'
  resources :user_reclamations
  resources :fichier_reclamations
  resources :fichiers
  resources :reclamations
  devise_for :views
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reclamation.rb
class Reclamation < ApplicationRecord
	has_many :user_reclamations
	has_many :fichier_reclamations
end

app/controllers/reclamations_controller.rb
class ReclamationsController < ApplicationController
  before_action :set_reclamation, only: [:show, :edit, :update, :destroy]

  # GET /reclamations
  # GET /reclamations.json
  def index
    @reclamations = Reclamation.all
  end

  # GET /reclamations/1
  # GET /reclamations/1.json
  def show
    @user_reclamations = UserReclamation.where(reclamation_id: @reclamation.id)
    @nouvelles = UserReclamation.where(vue: false, reclamation_id: @reclamation.id)
    @attentes = UserReclamation.where(vue: true ,resolu: false, reclamation_id: @reclamation.id)
    @valides = UserReclamation.where(resolu: true, reclamation_id: @reclamation.id)
  end

  # GET /reclamations/new
  def new
    @reclamation = Reclamation.new
  end

  # GET /reclamations/1/edit
  def edit
  end

  # POST /reclamations
  # POST /reclamations.json
  def create
    @reclamation = Reclamation.new(reclamation_params)

    respond_to do |format|
      if @reclamation.save
        format.html { redirect_to @reclamation, notice: 'Reclamation was successfully created.' }
        format.json { render :show, status: :created, location: @reclamation }
      else
        format.html { render :new }
        format.json { render json: @reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reclamations/1
  # PATCH/PUT /reclamations/1.json
  def update
    respond_to do |format|
      if @reclamation.update(reclamation_params)
        format.html { redirect_to @reclamation, notice: 'Reclamation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reclamation }
      else
        format.html { render :edit }
        format.json { render json: @reclamation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamations/1
  # DELETE /reclamations/1.json
  def destroy
    @reclamation.destroy
    respond_to do |format|
      format.html { redirect_to reclamations_url, notice: 'Reclamation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reclamation
      @reclamation = Reclamation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reclamation_params
      params.require(:reclamation).permit(:durre, :titre, :couleur)
    end
end

app/helpers/reclamations_helper.rb
module ReclamationsHelper
end

app/views/reclamations/_form.html.erb
<%= form_with(model: reclamation, local: true) do |form| %>
  <% if reclamation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reclamation.errors.count, "error") %> prohibited this reclamation from being saved:</h2>

      <ul>
        <% reclamation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :durre %>
    <%= form.number_field :durre %>
  </div>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :couleur %>
    <%= form.text_field :couleur %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reclamations/edit.html.erb
<h1>Editing Reclamation</h1>

<%= render 'form', reclamation: @reclamation %>

<%= link_to 'Show', @reclamation %> |
<%= link_to 'Back', reclamations_path %>

app/views/reclamations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reclamations</h1>

<table>
  <thead>
    <tr>
      <th>Durre</th>
      <th>Titre</th>
      <th>Couleur</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reclamations.each do |reclamation| %>
      <tr>
        <td><%= reclamation.durre %></td>
        <td><%= reclamation.titre %></td>
        <td><%= reclamation.couleur %></td>
        <td><%= link_to 'Show', reclamation %></td>
        <td><%= link_to 'Edit', edit_reclamation_path(reclamation) %></td>
        <td><%= link_to 'Destroy', reclamation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reclamation', new_reclamation_path %>

app/views/reclamations/new.html.erb
<h1>New Reclamation</h1>

<%= render 'form', reclamation: @reclamation %>

<%= link_to 'Back', reclamations_path %>

app/views/reclamations/show.html.erb
  <nav class="navbar navbar-default" style="background-color: #fff; box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.7); margin-bottom: 0px;">
    <div >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div> <!-- End of /.navbar-header -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-main" style="text-align: left;">
              <li><a href="/" style=" padding: 0px;"><img src="/vendor/images/logo.png" style="height: 80px;"></a></li>
                <li><a style="color: black; margin: 0px;" href="/">ACCUEIL</a></li>

              <!-- Dropdown Recrutement -->
              <li class="dropdown">
                  <a href="#" style="color: black; margin: 0px;">
                    RECLAMATION
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <% Reclamation.all.order(:titre).each do |r| %>
                      <li><a href="<%= reclamation_path(r.id) %>"><%= r.titre %></a></li>
                    <% end %>
                  </ul>
              </li>
              <li>
                <a style="color: black; margin: 0px;" href="<%= fichier_reclamation_path(1) %>">
                  <% if UserReclamation.where(resolu: true).count > 1 %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATIONS VALIDEES
                  <% else %>
                  <%= UserReclamation.where(resolu: true).count %> RECLAMATION VALIDEE
                  <% end %>
                </a>

              </li> 
            </ul> <!-- End of /.nav-main -->
        </div>  <!-- /.navbar-collapse -->
    </div>  <!-- /.container-fluid -->
    <div style="position: fixed; right: 20px; top: 20px; color: #fff;">
      <a href="#" class="btn btn-default" data-toggle="modal" data-target="#myModalDecon" style="border-radius: 50%;"><i class="fa fa-user fa-2x"></i></a>
    </div>
  </nav>  <!-- End of /.nav -->


<section>
  <br>
    <div class="container text-center" style="background-color: <%= @reclamation.couleur %>; box-shadow: 0px,0px,15px,0px, red; border-radius: 5px;">
      <div class="row">
        <div class="col-md-10">
          <h4 style="color: #fff;"><%= @reclamation.titre %></h4>
        </div>
          <div class="col-md-2" style="background-color: #fff; border-radius: 5px;">
            <h4><%= @user_reclamations.count %></h4>
          </div>
      </div>
    </div><br>
  <br>
  <div class="container" style="border: solid; border-width: 1px; border-color: #fff; background-color: rgba(0,0,0,0.5 ); min-height: 60vh;">
    <div class="col-md-4">
      <div style="background-color: #fff; text-align: center;">
        <% if @nouvelles.count > 0 %>
          <div style="position: absolute; background-color: red; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @nouvelles.count %></h5>
          </div>
        <% end %>
        <h5>Nouvelles réclamations</h5>
      </div>
      <% @nouvelles.each do |n| %>
        <div>
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= @reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><%= n.created_at.to_date %> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div style="background-color: #fff; text-align: center;">
        <% if @attentes.count > 0 %>
          <div style="position: absolute; background-color: red; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @attentes.count %></h5>
          </div>
        <% end %>
        <h5>Réclamations en attentes</h5>
      </div>
      <% @attentes.each do |n| %>
        <div>
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= @reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><%= n.created_at.to_date %> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div style="background-color: #fff; text-align: center;">
        <% if @valides.count > 0 %>
          <div style="position: absolute; background-color: #74a339; border-radius: 50%; min-width: 30px;">
            <h5 style="margin: 0px; color: #fff;"><%= @valides.count %></h5>
          </div>
        <% end %>
        <h5>Réclamations validées</h5>
      </div>
      <% @valides.reverse.each do |n| %>
        <div>
          <!--Accordion wrapper-->
            <div class="accordion md-accordion accordion-4" id="accordionEx<%= n.id %>" role="tablist" aria-multiselectable="true">
              <div class="card" style="background-color: <%= @reclamation.couleur %>; box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.7);">
                <!-- Card header -->
                  <div class="card-header z-depth-1 teal lighten-3" role="tab" id="heading1">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx<%= n.id %>" href="#collapse<%= n.id %>"
                      aria-expanded="false" aria-controls="collapse<%= n.id %>" style="color: #fff;">
                      <h6 class="container" style="color: #fff;">
                        <%= n.user.nom %>
                      </h6>  
                      <p class="text-right container" style="color: #fff;"><%= n.created_at.to_date %> <i class="fa fa-chevron-down"></i></p>
                    </a>
                  </div>
                  <!-- Card body -->
                  <div id="collapse<%= n.id %>" class="collapse" role="tabpanel" aria-labelledby="heading1" data-parent="#accordionEx<%= n.id %>" style="background-color: #fff; margin-bottom: 10px;/*border-left: solid; border-width: 0.5px; border-color: grey*/;">
                    <div class="card-body rgba-teal-strong white-text container">
                      <div class="text-center">
                        <p style="font-size: 1.2em; margin-top: 5px;" ><%= n.reclamation.titre %></p>
                        <p>NIF <%= n.user.nif %></p>
                      </div>
                      <% n.envoyers.each do |e| %>
                        <div class="text-right">
                          <p style="text-align: left;"><i class="fa fa-file"></i> <%= e.titre %> </p>
                          <object data="<%= e.contenu %>" height="50px"></object>
                        </div>
                      <% end %>

                      <div class="text-center">
                        <p><a href="<%= user_reclamation_path(n.id) %>" class="btn btn-warning" style="width: 90%;">Afficher</a></p>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
  <br>
</section>