config/routes.rb
Rails.application.routes.draw do
  resources :envoyers
  root 'fichier_reclamations#index'
  resources :user_reclamations
  resources :fichier_reclamations
  resources :fichiers
  resources :reclamations
  devise_for :views
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/fichier.rb
class Fichier < ApplicationRecord
	has_many :fichier_reclamations
end

app/controllers/fichiers_controller.rb
class FichiersController < ApplicationController
  before_action :set_fichier, only: [:show, :edit, :update, :destroy]

  # GET /fichiers
  # GET /fichiers.json
  def index
    @fichiers = Fichier.all
  end

  # GET /fichiers/1
  # GET /fichiers/1.json
  def show
  end

  # GET /fichiers/new
  def new
    @fichier = Fichier.new
  end

  # GET /fichiers/1/edit
  def edit
  end

  # POST /fichiers
  # POST /fichiers.json
  def create
    @fichier = Fichier.new(fichier_params)

    respond_to do |format|
      if @fichier.save
        format.html { redirect_to @fichier, notice: 'Fichier was successfully created.' }
        format.json { render :show, status: :created, location: @fichier }
      else
        format.html { render :new }
        format.json { render json: @fichier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fichiers/1
  # PATCH/PUT /fichiers/1.json
  def update
    respond_to do |format|
      if @fichier.update(fichier_params)
        format.html { redirect_to @fichier, notice: 'Fichier was successfully updated.' }
        format.json { render :show, status: :ok, location: @fichier }
      else
        format.html { render :edit }
        format.json { render json: @fichier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fichiers/1
  # DELETE /fichiers/1.json
  def destroy
    @fichier.destroy
    respond_to do |format|
      format.html { redirect_to fichiers_url, notice: 'Fichier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fichier
      @fichier = Fichier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fichier_params
      params.require(:fichier).permit(:titre, :contenu)
    end
end

app/helpers/fichiers_helper.rb
module FichiersHelper
end

app/views/fichiers/_form.html.erb
<%= form_with(model: fichier, local: true) do |form| %>
  <% if fichier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fichier.errors.count, "error") %> prohibited this fichier from being saved:</h2>

      <ul>
        <% fichier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :titre %>
  </div>

  <div class="field">
    <%= form.label :contenu %>
    <%= form.text_field :contenu %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fichiers/edit.html.erb
<h1>Editing Fichier</h1>

<%= render 'form', fichier: @fichier %>

<%= link_to 'Show', @fichier %> |
<%= link_to 'Back', fichiers_path %>

app/views/fichiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fichiers</h1>

<table>
  <thead>
    <tr>
      <th>Titre</th>
      <th>Contenu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fichiers.each do |fichier| %>
      <tr>
        <td><%= fichier.titre %></td>
        <td><%= fichier.contenu %></td>
        <td><%= link_to 'Show', fichier %></td>
        <td><%= link_to 'Edit', edit_fichier_path(fichier) %></td>
        <td><%= link_to 'Destroy', fichier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fichier', new_fichier_path %>

app/views/fichiers/new.html.erb
<h1>New Fichier</h1>

<%= render 'form', fichier: @fichier %>

<%= link_to 'Back', fichiers_path %>

app/views/fichiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titre:</strong>
  <%= @fichier.titre %>
</p>

<p>
  <strong>Contenu:</strong>
  <%= @fichier.contenu %>
</p>

<%= link_to 'Edit', edit_fichier_path(@fichier) %> |
<%= link_to 'Back', fichiers_path %>